version: '3.8'
services:
  mssql:
    build:
      context: ./mssql
    ports:
      - "1433:1433"
    volumes:
      - ./mssql/scripts:/usr/src/scripts/:ro
    environment:
      SA_PASSWORD: "yourStrongPassword!1"
      ACCEPT_EULA: "Y"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  flaskapp:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mssql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
    - ./frontend/flaskapp.conf:/etc/nginx/nginx.conf
    - ./frontend/templates:/usr/share/nginx/html
    depends_on: 
      - flaskapp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
