version: '3.8'
services:
  mssql:
    build:
      context: ./mssql
    ports:
      - "1433:1433"
    volumes:
      - ./mssql/scripts:/usr/src/scripts/:ro
    environment:
      SA_PASSWORD: "yourStrongPassword!1"
      ACCEPT_EULA: "Y"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mssql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
